### PR TITLE
Updated strings.xml (pt-PT)

### PR DESCRIPTION
**Pull request by DavidO-crypto**
Translated from English to Portuguese (pt-PT). 
Original file: "android/src/main/res/values/strings.xml".

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Hi, thanks for the contribution! Asked for a review in the portuguese community as I can't review myself.

**Review by Francis-Carvalho — CHANGES_REQUESTED** [review]
I have found some typos and misspallings.

In line 39: "à uns momentos atrás" must be replaced for: "Há uns momentos atrás"
In line 43: "Erro ao iniciar a câmera. Por favor verifique as suas definições de privaidade." must be replaced for: "Erro ao iniciar a câmera. Por favor verifique as suas definições de privacidade."
In line 46: "Avance com cuidade, tendo o conhecimento acima." must be replaced for: "Avance com cuidado, tendo o conhecimento acima."
In line 113: the question mark is unnecessary
In line 192: the question mark is unnecessary

**Comment by MrStahlfelge** [comment]
@DavidO-crypto can you compile the change requests?

**Comment by DavidO-crypto** [comment]
Hello, the changes were applied. Thank you @Francis-Carvalho @MrStahlfelge

**Review by MrStahlfelge — APPROVED** [review]

**Pull request merged**
